[package]
name = "ducc-serde"
version = "0.1.0"
authors = ["Skyler Lipthay <sl@skylerlipthay.com>"]
repository = "https://github.com/SkylerLipthay/ducc"
license = "MIT"

[dependencies]
serde = "1.0"

[dependencies.ducc]
path = "../ducc"
